on:
  push:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  release:
    types: [published, created, edited]

jobs:
  CICD:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: Rscript {0}
    # this needs to be the same as in Dockerfile
    container: subugoe/muggle-onbuild:f60004c31979947dab53fbf9cfbb0e7f1c4bea55
    steps:
      - uses: actions/checkout@v2
      - name: Cache R Packages
        uses: actions/cache@v2
        with:
          # only cache the user library
          path: ".github/library"
          key: ${{ job.container.image }}-${{ hashFiles('DESCRIPTION') }}
      - name: Install System Dependencies
        run: muggle::install_sysdeps()
      - name: Install R Dependencies
        env:
          # see builder.Dockerfile for explanation, this resets after this step
          R_LIBS_SITE: $R_LIBS_APP_GH
        run: remotes::install_deps(dependencies = TRUE)
      - name: Check
        run: muggle::rcmdcheck2()
      - name: Test Coverage
        run: covr::codecov()
      - name: Build Package Website
        run: |
          # extra step is necessary to build index.md to integrate readme and landing page
          rmarkdown::render("pkgdown/index.Rmd")
          pkgdown::build_site(override = list(new_process = FALSE))
      - uses: docker/build-push-action@v1
        name: Build Dev Image
        with:
          repository: ${{ github.repository }}/hoad-dev
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          # this will set "latest" if master as per https://github.com/docker/build-push-action
          tag_with_ref: true
          # we're relying on long shas only to keep things easy
          tag_with_sha: false
          tags: ${{ github.sha }}
          add_git_labels: true
          push: ${{ github.event_name != 'pull_request' }}
      - name: Setup GCP Cloud SDK
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: gcloud info
        shell: bash
      - name: Deploy to GCP
        if: github.event_name != 'pull_request'
        uses: GoogleCloudPlatform/github-actions/appengine-deploy@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Deploy Shiny Application to shinyapps.io ref
        env:
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
          GITHUB_REF: ${{ github.ref }}
        if: github.event_name != 'pull_request'
        run: |
          remotes::install_github(repo = "subugoe/hoad", ref = "master", force = TRUE, dependencies = TRUE)
          rsconnect::setAccountInfo(name = 'subugoe', token = Sys.getenv('SHINYAPPS_TOKEN'), secret = Sys.getenv('SHINYAPPS_SECRET'))
          app_name <- paste0("hoad-", gsub("/", "-", Sys.getenv('GITHUB_REF')))
          rsconnect::deployDoc(doc = "inst/app/dashboard.Rmd", appName = app_name)
        shell: Rscript {0}
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: maxheld83/ghpages@github-token
        env:
          BUILD_DIR: docs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
